#!/bin/bash
#PBS -l nodes=1:ppn=4
#PBS -l walltime=04:00:00
#PBS -l pmem=16gb
#PBS -A cdm8_f_g_bc_default

# bash command - treat unset variables as an error when substituting
set -u

# get started
echo " "
echo "Job started on `hostname` at `date`"
echo " "

# remove all previously loaded modules
module purge
# load matlab 
module load matlab

# cd to work directory from where to run the scripts
# cd /storage/home/sxs2737/work/kfit
# use this line of qsub is execuited from the working directory
cd $PBS_O_WORKDIR

# run command
matlab -nodisplay -nosplash < run_test.m > log.matlabRun

# move log file to relevant folder
mv log.matlabRun logs/

# Finish
echo " "
echo "Job Finished at `date`"
echo " "